language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo test -p ethereum-types
  - cargo test -p ethbloom
  - cargo +nightly test -p no-std-tests
env:
  - RUST_LOG=quickcheck
