[package]
name = "ethereum-types"
version = "0.5.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
homepage = "https://github.com/paritytech/primitives"
description = "Ethereum types"

[dependencies]
crunchy = { version = "0.2.1", default-features = false }
ethbloom = { path = "../ethbloom", version = "0.6", default-features = false }
ethereum-types-serialize = { version = "0.2.1", path = "../serialize", optional = true }
fixed-hash = { version = "0.3", default_features = false }
serde = { version = "1.0", optional = true }
uint = { version = "0.5", default_features = false }

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["std", "heapsize", "serialize", "fixed-hash/byteorder", "fixed-hash/rustc-hex"]
std = ["uint/std", "fixed-hash/std", "ethbloom/std", "crunchy/std"]
heapsize = ["uint/heapsize", "fixed-hash/heapsize", "ethbloom/heapsize"]
serialize = ["std", "ethereum-types-serialize", "serde", "ethbloom/serialize"]
